### ISSUE TITLE
Mistake in get_ohlc format.

### ISSUE THREAD

**Issue by emanistanton** [rickykim93/gcapi-python#7]
in gcapi_client ---> in def get_ohlc:

Original:  if from_ts is not None and to_ts is not None:
			r = self.session.get(
				self.rest_url + f'/market/{market_id}/barhistorybetween?interval={interval}&span={span}fromTimeStampUTC={from_ts}&toTimestampUTC={to_ts}')

'&' should be added between these parts so that the request is valid. {span} ---- fromTimeStampUTC

Corrected: if from_ts is not None and to_ts is not None:
			r = self.session.get(
				self.rest_url + f'/market/{market_id}/barhistorybetween?interval={interval}&span={span}&fromTimeStampUTC={from_ts}&toTimestampUTC={to_ts}')

**Comment by rickykim93** [comment]
fixed
